baseURL = 'https://www.py20555sti.com'
languageCode = 'en-us'
title = 'PY20555STI'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]

[params]
  featured_image = "/images/arena_banner.jpg"
  [[menu.main]]
    name ="Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"
    disable=false
  [[module.imports]]
    path = "github.com/mfg92/hugo-shortcode-gallery"
    disable=false
